appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: qWBibmX112T8FwZnp9AxRwc2PzmodrbpRlNSuqYCeOzrJPpI9lO5+GTrxLgJI50Fmj8VRyzQ6b1F1XvxXFGQdzT/bzOOY3AGkAzldqEsNofotjhFU1DAH4C3eptXDVMyTUpPW9pbIaBiqWa3geciwxiXtF2HQgDNh8M8qNEQBzxY6nDIeQ5alXo+xRuYoevN6EzStNK5liPBtsdsksT9h2m2vBSOqWfrzgg6a2XKLsKD8uVhaXaAp3nocTLn4yaFtShO6CPjqaq+hp8zdZCiW+LgkvKDgo73AQxrgZP8agRKAFnAA9WKM9U2WhbzOdcuq9a+HLBmcG+F7s7Lga2yyFB8UiF5L9l1FPjj3WejQHroHKUpuqU8yLA8Q8Y9sGIWifIUPSBDPLQR0k212KuzxquIesXCOckzK4JVOvDuVXf0mH/ZS36BPK5Ps+3+RmxUWmBqoZRcTFLLbkr0RbltV1CqfoTtPa7TP9m2qTVvN+qAFUQrDUIqj2+yCMUPyK6UNDpssYHGOEffDkSqyusWK4oTD//H6XULlmxLqwawElFblAiGzl6josw6eOPbkzakRTa4AO0ftBdFwZ6nJofKxYhIEtHJAuqmBvyKNFARWwzx/XzMwcVL5ZsisJlXJlW+9JRoZtGmsWbjrnaeK/lP3IjW05BhBhZNrbkxOnE8tss=}
bot:
  automerge: true
