travis:
  secure:
    BINSTAR_TOKEN: M0eNA81cRihdkBTq6DZk2MjstPYH4eFvI5y5rOwgTPY+x81Y0YU7p6MCdPM9Br51OKBP7V2AlvPGQCJpt40TrZJe0SHLEzK9Iri5Ti6oPElYNDnIDIP75MOdEViji3xGkYZ8hokMs3bpdEi+VNa9gxV8onzdIyfe0gBDqEG4NAqR/DgWaBGw92b/rbjimoFjxbKVez4xpq3NXky6PYf/iyFJ0EvkAu8R0MrG4P4VSfQTPKaVl387jicrk9W4FgZEalSTJE9V+v8qkGY3wXKldqMhKuzDFFN70hi2uTQUuWmm5Dnc8h9GoGqhZwouVrXWrCm3XN7iIeDVmKYfmzGJXNYtnmVJ3fvhlRLpsmXnsWFo22iKzxXDalSc8MeuD9Q34vf428qrs3ItzddCKL/u+zy9gZeD8Nnrdl0pJXqaVUFIHOnutGTO+en64XLDp32Nv+EVg/B0E6JQCVwF8SPhJzqeBej30wj7SgrYhgHhdfSaoOFzmyJ1aQDYtjlYITuzSNgk+nGxWAeveGIidI+19Tgt8qyfD3bQOWkNyTywu0eiDFKcO5Msr9kw064caIb5hJ19RaBi2yitcSRCsPLe2Jpn5TvO+NytwlsBtMfWBKTK6FLLtHyv05tUv7O1+VW87xr+Qc+Q78Hl1ixZZV1i1RIDACUYWvMbSO42eOwJh50=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
